# Generated by Django 2.0.5 on 2018-05-16 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrument',
            name='calibration_cost',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Calibration Cost'),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='calibration_date',
            field=models.DateField(blank=True, null=True, verbose_name='Calibration Date'),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='calibration_expiry_date',
            field=models.DateField(blank=True, null=True, verbose_name='Calibration Expiry Date'),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='certificate_number',
            field=models.CharField(blank=True, max_length=65, null=True, verbose_name='Certificate Number'),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='description',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='instrument_id',
            field=models.CharField(max_length=65, unique=True, verbose_name='Instrument ID'),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='item_id',
            field=models.CharField(blank=True, max_length=65, null=True, verbose_name='Item ID'),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='manufacturer',
            field=models.CharField(blank=True, max_length=65, null=True, verbose_name='Manufacturer'),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='max_operating_range',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Maximum Operating Range'),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='min_operating_range',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Minimum Operating Range'),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='model',
            field=models.CharField(blank=True, max_length=65, null=True, verbose_name='Model'),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='serial_number',
            field=models.CharField(blank=True, max_length=65, null=True, verbose_name='Serial Number'),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='tolerance',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Tolerance'),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='value',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Value'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_id',
            field=models.CharField(max_length=45, unique=True, verbose_name='Project ID'),
        ),
    ]
